baseUrl: "http://localhost:8080/"
getTaxRecord: "/calculator/taxRelief"
insertMultipleRecord: "calculator/insertMultiple"
insertSingleRecord: "calculator/insert"
birthDay: "11041982"
gender: "male"
name: "test"
natid: "1001"
salary: "100000"
tax: "1233"
